# Generated by Django 5.0.9 on 2024-11-04 09:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='review_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('birth_certificate', 'Birth Certificate'), ('high_school_diploma', 'High School Diploma'), ('good_moral', 'Good Moral Certificate'), ('medical_certificate', 'Medical Certificate')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('user', 'document_type')},
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['user', 'document_type'], name='FileApp_doc_user_id_8ea1fd_idx'),
        ),
    ]
