# Generated by Django 5.0.9 on 2024-11-13 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileApp', '0003_alter_document_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('birth_certificate', 'Birth Certificate'), ('form_137', 'Form 137'), ('transcript_of_records', 'Transcript of Records'), ('high_school_diploma', 'High School Diploma'), ('good_moral', 'Good Moral Certificate'), ('two_x_two_photo', 'Two by Two Picture'), ('certificate_of_transfer', 'Certificate of Transfer'), ('medical_certificate', 'Medical Certificate'), ('profile', 'Profile Picture')], max_length=50),
        ),
    ]
