# Generated by Django 5.0.9 on 2024-11-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileApp', '0004_alter_document_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
