# Generated by Django 5.0.9 on 2024-11-14 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileApp', '0005_document_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('birth_certificate', 'birth_certificate'), ('form_137', 'form_137'), ('transcript_of_records', 'transcript_of_records'), ('high_school_diploma', 'high_school_diploma'), ('good_moral', 'good_moral'), ('two_x_two_photo', 'two_x_two_photo'), ('certificate_of_transfer', 'certificate_of_transfer'), ('medical_certificate', 'medical_certificate'), ('profile', 'profile')], max_length=50),
        ),
    ]
