# Generated by Django 5.0.9 on 2024-11-28 16:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileApp', '0006_alter_document_document_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AdminContactDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('image', 'Image'), ('pdf', 'PDF Document'), ('other', 'Other')], max_length=10)),
                ('cloudinary_public_id', models.CharField(max_length=255)),
                ('cloudinary_resource_type', models.CharField(max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_size', models.IntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('admin_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='FileApp.admincontact')),
            ],
        ),
    ]
