# Generated by Django 5.0.9 on 2024-11-13 01:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fulldata_applicant_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
