# Generated by Django 5.0.9 on 2024-11-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_employee_id_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fulldata_applicant_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
