# Generated by Django 5.0.9 on 2024-11-28 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_fulldata_applicant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
