POST http://127.0.0.1:8000/api/register
Content-Type: application/json

{ "name": "non","student_id": "2024-01-0003", "email": "qwe2@mail.com", "password": "Pass1234!"  }

###

POST http://127.0.0.1:8000/api/login 
Content-Type: application/json

{ "student_id": "2024-01-0999", "password": "default123123" }


###

GET http://127.0.0.1:8000/api/user
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI2NDE0NDQ3LCJpYXQiOjE3MjY0MTQxNDcsImp0aSI6Ijk3YzhhYWJkNjhmMzRjN2Y5ZTcxOGExMTEzZWRhZDIzIiwidXNlcl9pZCI6Mn0.XrT0GZw8tILOSGsrokPHi6daAgWnT-GRcCmPTa4DPtY