# Generated by Django 5.0.3 on 2024-03-17 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TblRoomInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=255)),
                ('floor_lvl', models.CharField(max_length=255)),
                ('room_no', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TblStdntInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=255)),
                ('m_name', models.CharField(max_length=255)),
                ('l_name', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(max_length=255)),
                ('civil_stat', models.CharField(max_length=255)),
                ('citizenship', models.CharField(max_length=255)),
                ('religion', models.CharField(max_length=255)),
                ('ImageData', models.BinaryField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TblUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('user_level', models.CharField(max_length=255)),
                ('user_role', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TblCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('department_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DangoDBApp.tbldepartment')),
            ],
        ),
        migrations.CreateModel(
            name='TblStaffInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=255)),
                ('m_name', models.CharField(max_length=255)),
                ('l_name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DangoDBApp.tbldepartment')),
            ],
        ),
        migrations.CreateModel(
            name='TblAddStaffInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_address', models.TextField()),
                ('contact_info', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('active', models.BooleanField(default=True)),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DangoDBApp.tblstaffinfo')),
            ],
        ),
        migrations.CreateModel(
            name='TblAddStdntInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stdnt_address', models.TextField()),
                ('contact_info', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('active', models.BooleanField(default=True)),
                ('stdnt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DangoDBApp.tblstdntinfo')),
            ],
        ),
        migrations.CreateModel(
            name='TblStdntSchoolDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('yr_lvl', models.CharField(max_length=255)),
                ('semester', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('stdnt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DangoDBApp.tblstdntinfo')),
            ],
        ),
        migrations.CreateModel(
            name='TblSubjInfo',
            fields=[
                ('offercode', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Description', models.TextField()),
                ('subject_code', models.CharField(max_length=255)),
                ('unit', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DangoDBApp.tblcourse')),
            ],
        ),
        migrations.CreateModel(
            name='TblStdntSubj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('stdnt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DangoDBApp.tblstdntinfo')),
                ('offercode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DangoDBApp.tblsubjinfo')),
            ],
        ),
        migrations.CreateModel(
            name='TblSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_day', models.CharField(max_length=255)),
                ('class_hour', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DangoDBApp.tblroominfo')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DangoDBApp.tblstaffinfo')),
                ('offercode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DangoDBApp.tblsubjinfo')),
            ],
        ),
    ]
