# Generated by Django 5.0.9 on 2024-10-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblcampus',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
