# Generated by Django 5.0.9 on 2024-10-03 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TblAddPersonalData',
            new_name='TblStudentAddPersonalData',
        ),
    ]
