# Generated by Django 5.0.3 on 2024-03-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblstdntinfo',
            name='citizenship',
        ),
        migrations.RemoveField(
            model_name='tblstdntinfo',
            name='religion',
        ),
        migrations.AlterField(
            model_name='tblstdntinfo',
            name='birth_date',
            field=models.DateTimeField(),
        ),
    ]
