# Generated by Django 5.0.9 on 2024-10-13 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TblGradingPeriod',
        ),
        migrations.DeleteModel(
            name='TblRoomInfo',
        ),
        migrations.DeleteModel(
            name='TblUsers',
        ),
    ]
