# Generated by Django 5.0.9 on 2024-11-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblcourse',
            name='campus_id',
        ),
        migrations.AlterField(
            model_name='tblschedule',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tblschedule',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
