# Generated by Django 5.0.2 on 2024-03-07 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tblstdntschooldetails',
            old_name='stdnt',
            new_name='stdnt_id',
        ),
        migrations.AddField(
            model_name='tblcourse',
            name='department_Id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DangoDBApp.tbldepartment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tbladdstdntinfo',
            name='stdnt_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DangoDBApp.tblstdntinfo'),
        ),
        migrations.AlterField(
            model_name='tbladdteacherinfo',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DangoDBApp.tblteacherinfo'),
        ),
        migrations.AlterField(
            model_name='tblschedule',
            name='offercode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DangoDBApp.tblsubjinfo'),
        ),
        migrations.AlterField(
            model_name='tblstdntsubj',
            name='offercode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DangoDBApp.tblsubjinfo'),
        ),
    ]
