# Generated by Django 5.0.9 on 2024-11-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0002_remove_tblcourse_campus_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblschedule',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='tblschedule',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
