# Generated by Django 5.0.3 on 2024-03-13 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0002_rename_stdnt_tblstdntschooldetails_stdnt_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblcourse',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
