# Generated by Django 5.0.9 on 2024-10-13 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0002_delete_tblgradingperiod_delete_tblroominfo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblprogram',
            name='program',
            field=models.CharField(max_length=255, verbose_name='Program Name'),
        ),
    ]
