# Generated by Django 5.0.9 on 2024-10-03 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0002_rename_tbladdpersonaldata_tblstudentaddpersonaldata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblstudentacademicbackground',
            name='department',
        ),
    ]
