# Generated by Django 5.0.3 on 2024-03-21 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0002_remove_tblstdntinfo_citizenship_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblstdntschooldetails',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DangoDBApp.tblcourse'),
        ),
        migrations.AlterField(
            model_name='tblstdntschooldetails',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DangoDBApp.tbldepartment'),
        ),
    ]
