# Generated by Django 5.0.9 on 2024-10-13 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0003_alter_tblprogram_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblprogram',
            name='program',
            field=models.CharField(max_length=255),
        ),
    ]
