# Generated by Django 5.0.9 on 2024-10-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0003_alter_tblcampus_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbldepartment',
            name='created_at',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='tbldepartment',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tbldepartment',
            name='updated_at',
            field=models.CharField(max_length=225),
        ),
    ]
