# Generated by Django 5.0.9 on 2024-10-03 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0003_remove_tblstudentacademicbackground_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tblprogram',
            old_name='department_Id',
            new_name='department_id',
        ),
        migrations.RemoveField(
            model_name='tblstudentofficialinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='tblstudentacademicbackground',
            name='fulldata_applicant_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='related_acedemicbackground_data', to='DangoDBApp.tblstudentpersonaldata'),
        ),
        migrations.AlterField(
            model_name='tblstudentacademichistory',
            name='fulldata_applicant_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='related_academichistory_data', to='DangoDBApp.tblstudentpersonaldata'),
        ),
        migrations.AlterField(
            model_name='tblstudentaddpersonaldata',
            name='fulldata_applicant_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='related_addpersonal_data', to='DangoDBApp.tblstudentpersonaldata'),
        ),
        migrations.AlterField(
            model_name='tblstudentfamilybackground',
            name='fulldata_applicant_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='related_family_data', to='DangoDBApp.tblstudentpersonaldata'),
        ),
        migrations.AlterField(
            model_name='tblstudentofficialinfo',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='tblstudentofficialinfo',
            name='student_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tblstudentpersonaldata',
            name='basicdata_applicant_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='related_personal_data', to='DangoDBApp.tblstudentbasicinfo'),
        ),
        migrations.AlterUniqueTogether(
            name='tblstudentpersonaldata',
            unique_together={('f_name', 'm_name', 'suffix', 'l_name', 'sex', 'birth_date', 'birth_place', 'marital_status', 'religion', 'country', 'email', 'acr', 'status')},
        ),
    ]
