# Generated by Django 5.0.3 on 2024-03-13 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0003_tblcourse_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbladdstdntinfo',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tbladdteacherinfo',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tbldepartment',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tblroominfo',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tblschedule',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tblstdntinfo',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tblstdntschooldetails',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tblstdntsubj',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tblsubjinfo',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tblteacherinfo',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tblusers',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
