# Generated by Django 5.0.9 on 2024-11-09 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0003_alter_tblschedule_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblcourse',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tblcourse',
            name='department_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DangoDBApp.tbldepartment'),
        ),
    ]
