# Generated by Django 5.0.3 on 2024-04-15 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0003_alter_tblstudentacademicbackground_year_entry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblstudentacademichistory',
            name='Secondary_graduate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tblstudentacademichistory',
            name='elementary_graduate',
            field=models.DateField(),
        ),
    ]
