# Generated by Django 5.0.9 on 2024-11-09 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0004_alter_tblcourse_code_alter_tblcourse_department_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblschedule',
            name='recurrence_pattern',
            field=models.TextField(blank=True, null=True),
        ),
    ]
