# Generated by Django 5.0.9 on 2024-10-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0004_alter_tbldepartment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblprogram',
            name='created_at',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='tblprogram',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tblprogram',
            name='updated_at',
            field=models.CharField(max_length=225),
        ),
    ]
