# Generated by Django 5.0.9 on 2024-10-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0004_rename_department_id_tblprogram_department_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblstudentacademicbackground',
            name='year_level',
            field=models.CharField(default='1st Year', max_length=8),
            preserve_default=False,
        ),
    ]
