# Generated by Django 5.0.3 on 2024-03-16 16:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0004_tbladdstdntinfo_active_tbladdteacherinfo_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblsubjinfo',
            name='course_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DangoDBApp.tblcourse'),
            preserve_default=False,
        ),
    ]
