# Generated by Django 5.0.3 on 2024-04-15 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0004_alter_tblstudentacademichistory_secondary_graduate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tblstudentacademichistory',
            old_name='Secondary_address',
            new_name='secondary_address',
        ),
        migrations.RenameField(
            model_name='tblstudentacademichistory',
            old_name='Secondary_graduate',
            new_name='secondary_graduate',
        ),
        migrations.RenameField(
            model_name='tblstudentacademichistory',
            old_name='Secondary_honors',
            new_name='secondary_honors',
        ),
        migrations.RenameField(
            model_name='tblstudentacademichistory',
            old_name='Secondary_school',
            new_name='secondary_school',
        ),
        migrations.RemoveField(
            model_name='tblsomething',
            name='f_name',
        ),
        migrations.RemoveField(
            model_name='tblsomething',
            name='l_name',
        ),
        migrations.RemoveField(
            model_name='tblsomething',
            name='m_name',
        ),
    ]
