# Generated by Django 5.0.9 on 2024-10-13 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0004_alter_tblprogram_program'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tblbugreport',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='tbldepartment',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='tblprogram',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='tblstudentacademicbackground',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='tblstudentacademichistory',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='tblstudentaddpersonaldata',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='tblstudentbasicinfo',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='tblstudentfamilybackground',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='tblstudentofficialinfo',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='tblstudentpersonaldata',
            old_name='active',
            new_name='is_active',
        ),
    ]
