# Generated by Django 5.0.9 on 2024-11-13 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0005_alter_tblschedule_recurrence_pattern'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblstudentacademicbackground',
            name='major_in',
            field=models.TextField(blank=True, null=True),
        ),
    ]
