# Generated by Django 5.1 on 2024-08-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0005_rename_secondary_address_tblstudentacademichistory_secondary_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tblschedule',
            old_name='class_hour',
            new_name='class_hour_end',
        ),
        migrations.AddField(
            model_name='tblschedule',
            name='class_hour_start',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
