# Generated by Django 5.0.9 on 2024-10-03 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0005_tblstudentacademicbackground_year_level'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tbldepartment',
            unique_together={('department_name', 'campus_id', 'department_code', 'department_dean')},
        ),
        migrations.AlterUniqueTogether(
            name='tblprogram',
            unique_together={('program', 'department_id')},
        ),
    ]
