# Generated by Django 5.0.9 on 2024-10-13 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0006_rename_department_code_tbldepartment_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255, null=True)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255)),
                ('qualifications', models.JSONField(null=True)),
                ('gender', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=95)),
                ('birth_date', models.DateField()),
                ('contact_number', models.CharField(max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DangoDBApp.tblcampus')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DangoDBApp.tbldepartment')),
            ],
        ),
        migrations.AlterField(
            model_name='tbldepartment',
            name='dean',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DangoDBApp.tblemployee'),
        ),
    ]
