# Generated by Django 5.0.9 on 2024-11-13 05:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0006_alter_tblstudentacademicbackground_major_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblschedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tblschedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
