# Generated by Django 5.0.9 on 2024-10-31 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0006_alter_tblsemester_created_at_alter_tblsemester_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblstudentpersonaldata',
            name='on_site',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tblstudentacademicbackground',
            name='year_level',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tblstudentpersonaldata',
            name='basicdata_applicant_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_basic_data', to='DangoDBApp.tblstudentbasicinfo'),
        ),
        migrations.AlterField(
            model_name='tblstudentpersonaldata',
            name='status',
            field=models.CharField(choices=[('officially enrolled', 'Officially Enrolled'), ('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('initially enrolled', 'Initially Enrolled')], default='pending', max_length=20),
        ),
    ]
