# Generated by Django 5.0.9 on 2024-10-22 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0006_alter_tblsemester_created_at_alter_tblsemester_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblstudentacademicbackground',
            name='year_level',
            field=models.CharField(max_length=50),
        ),
    ]
