# Generated by Django 5.0.9 on 2024-10-04 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0006_alter_tbldepartment_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblstudentaddpersonaldata',
            name='fulldata_applicant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_addpersonal_data', to='DangoDBApp.tblstudentpersonaldata'),
        ),
    ]
