# Generated by Django 5.1 on 2024-08-18 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0006_rename_class_hour_tblschedule_class_hour_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblGrades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('active', models.BooleanField(default=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DangoDBApp.tbladdstaffinfo')),
                ('offercode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DangoDBApp.tblsubjinfo')),
                ('semester_and_academicyr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DangoDBApp.tblstudentacademicbackground')),
                ('stdnt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DangoDBApp.tblstudentpersonaldata')),
            ],
        ),
        migrations.CreateModel(
            name='TblGradingPeriod',
            fields=[
                ('period_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TblStdntSubjEnrolled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('Schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DangoDBApp.tblschedule')),
                ('offercode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DangoDBApp.tblsubjinfo')),
                ('stdnt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DangoDBApp.tblstudentpersonaldata')),
            ],
        ),
        migrations.RemoveField(
            model_name='tbladdstdntinfo',
            name='stdnt_id',
        ),
        migrations.DeleteModel(
            name='TblSomething',
        ),
        migrations.RemoveField(
            model_name='tblstdntschooldetails',
            name='stdnt_id',
        ),
        migrations.RemoveField(
            model_name='tblstdntsubj',
            name='stdnt',
        ),
        migrations.RemoveField(
            model_name='tblstdntschooldetails',
            name='course',
        ),
        migrations.RemoveField(
            model_name='tblstdntschooldetails',
            name='department',
        ),
        migrations.RemoveField(
            model_name='tblstdntsubj',
            name='offercode',
        ),
        migrations.AddField(
            model_name='tblgrades',
            name='grading_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DangoDBApp.tblgradingperiod'),
        ),
        migrations.DeleteModel(
            name='TblAddStdntInfo',
        ),
        migrations.DeleteModel(
            name='TblStdntInfo',
        ),
        migrations.DeleteModel(
            name='TblStdntSchoolDetails',
        ),
        migrations.DeleteModel(
            name='TblStdntSubj',
        ),
    ]
