# Generated by Django 5.0.9 on 2024-10-31 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DangoDBApp", "0007_alter_tblstudentacademicbackground_year_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="tblstudentpersonaldata",
            name="on_site",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="tblstudentpersonaldata",
            name="status",
            field=models.CharField(
                choices=[
                    ("officially enrolled", "Officially Enrolled"),
                    ("pending", "Pending"),
                    ("verified", "Verified"),
                    ("rejected", "Rejected"),
                    ("initially enrolled", "Initially Enrolled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
