# Generated by Django 5.1 on 2024-08-18 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0007_tblgrades_tblgradingperiod_tblstdntsubjenrolled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblgrades',
            name='offercode',
        ),
        migrations.AddField(
            model_name='tblgrades',
            name='Subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DangoDBApp.tblstdntsubjenrolled'),
            preserve_default=False,
        ),
    ]
