# Generated by Django 5.0.9 on 2024-10-31 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0007_tblstudentpersonaldata_on_site_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblstudentpersonaldata',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
