# Generated by Django 5.0.9 on 2024-11-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0007_tblschedule_created_at_tblschedule_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblstudentpersonaldata',
            name='status',
            field=models.CharField(choices=[('officially enrolled', 'officially enrolled'), ('pending', 'pending'), ('rejected', 'rejected'), ('initially enrolled', 'initially enrolled')], default='pending', max_length=20),
        ),
    ]
