# Generated by Django 5.0.9 on 2024-10-07 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0008_tblstudentofficialinfo_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblstudentpersonaldata',
            name='basicdata_applicant_id',
        ),
    ]
