# Generated by Django 5.0.9 on 2024-11-14 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0008_alter_tblstudentpersonaldata_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TblStudentEnlistedSubjects',
        ),
    ]
