# Generated by Django 5.0.9 on 2024-11-01 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0008_alter_tblstudentpersonaldata_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblStudentEnlistedSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_enlisted_subjects', to='DangoDBApp.tblclass')),
                ('fulldata_applicant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_enlistedsubj_data', to='DangoDBApp.tblstudentpersonaldata')),
            ],
        ),
    ]
