# Generated by Django 5.0.9 on 2024-10-31 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DangoDBApp", "0008_tblstudentpersonaldata_on_site_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tblstudentpersonaldata",
            name="on_site",
            field=models.BooleanField(default=False),
        ),
    ]
