# Generated by Django 5.1 on 2024-08-20 07:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0008_remove_tblgrades_offercode_tblgrades_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblstudentacademichistory',
            name='ncar',
        ),
        migrations.RemoveField(
            model_name='tblstudentacademichistory',
            name='secondary_address',
        ),
        migrations.RemoveField(
            model_name='tblstudentacademichistory',
            name='secondary_graduate',
        ),
        migrations.RemoveField(
            model_name='tblstudentacademichistory',
            name='secondary_honors',
        ),
        migrations.RemoveField(
            model_name='tblstudentacademichistory',
            name='secondary_school',
        ),
        migrations.AddField(
            model_name='tblstudentacademichistory',
            name='junior_address',
            field=models.TextField(default='Not Provided'),
        ),
        migrations.AddField(
            model_name='tblstudentacademichistory',
            name='junior_graduate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tblstudentacademichistory',
            name='junior_highschool',
            field=models.TextField(default='Not Provided'),
        ),
        migrations.AddField(
            model_name='tblstudentacademichistory',
            name='junior_honors',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='tblstudentacademichistory',
            name='ncae_grade',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='tblstudentacademichistory',
            name='ncae_year_taken',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tblstudentacademichistory',
            name='senior_address',
            field=models.TextField(default='Not Provided'),
        ),
        migrations.AddField(
            model_name='tblstudentacademichistory',
            name='senior_graduate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tblstudentacademichistory',
            name='senior_highschool',
            field=models.TextField(default='Not Provided'),
        ),
        migrations.AddField(
            model_name='tblstudentacademichistory',
            name='senior_honors',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='tblstudentacademichistory',
            name='college_address',
            field=models.TextField(default='Not Provided'),
        ),
        migrations.AlterField(
            model_name='tblstudentacademichistory',
            name='college_honors',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='tblstudentacademichistory',
            name='course',
            field=models.TextField(default='Not Specified'),
        ),
        migrations.AlterField(
            model_name='tblstudentacademichistory',
            name='elementary_address',
            field=models.TextField(default='Not Provided'),
        ),
        migrations.AlterField(
            model_name='tblstudentacademichistory',
            name='elementary_graduate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tblstudentacademichistory',
            name='elementary_honors',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='tblstudentacademichistory',
            name='elementary_school',
            field=models.TextField(default='Not Provided'),
        ),
        migrations.AlterField(
            model_name='tblstudentacademichistory',
            name='latest_college',
            field=models.TextField(default='Not Provided'),
        ),
    ]
