# Generated by Django 5.0.9 on 2024-10-07 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0009_remove_tblstudentpersonaldata_basicdata_applicant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblstudentacademicbackground',
            name='fulldata_applicant_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='related_academicbackground_data', to='DangoDBApp.tblstudentpersonaldata'),
        ),
    ]
