# Generated by Django 5.0.9 on 2024-11-14 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0009_delete_tblstudentenlistedsubjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblStudentProspectus',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('year_level', models.CharField(max_length=50)),
                ('semester_name', models.CharField(max_length=50)),
                ('program_id', models.IntegerField()),
                ('prerequisite', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField()),
                ('is_deleted', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DangoDBApp.tblcourse')),
            ],
        ),
    ]
