# Generated by Django 5.0.9 on 2024-11-01 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0009_tblstudentenlistedsubjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblemployee',
            name='campus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DangoDBApp.tblcampus'),
        ),
        migrations.AlterField(
            model_name='tblemployee',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DangoDBApp.tbldepartment'),
        ),
    ]
