# Generated by Django 5.1 on 2024-08-22 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0010_alter_tblstudentacademicbackground_semester_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblAddPersonalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_address', models.TextField()),
                ('province_address', models.TextField()),
                ('contact_number', models.CharField(max_length=30)),
                ('city_contact_number', models.CharField(max_length=30)),
                ('province_contact_number', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('citizenship', models.CharField(max_length=70)),
                ('active', models.BooleanField(default=True)),
                ('stdnt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DangoDBApp.tblstudentpersonaldata')),
            ],
        ),
    ]
