# Generated by Django 5.0.9 on 2024-10-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0010_alter_tblstudentacademicbackground_fulldata_applicant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblstudentpersonaldata',
            name='status',
            field=models.CharField(choices=[('officially enrolled', 'Officially Enrolled'), ('pending', 'Pending'), ('rejected', 'Rejected'), ('initially enrolled', 'Initially Enrolled')], default='pending', max_length=20),
        ),
    ]
