# Generated by Django 5.0.9 on 2024-11-14 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0010_tblstudentprospectus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TblStudentProspectus',
            new_name='TblProspectus',
        ),
    ]
