# Generated by Django 5.0.9 on 2024-11-01 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0010_alter_tblemployee_campus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblclass',
            name='subject',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tblclass',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DangoDBApp.tblprogram'),
        ),
    ]
