# Generated by Django 5.0.9 on 2024-11-01 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0011_tblclass_subject_alter_tblclass_program'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tblstudentenlistedsubjects',
            unique_together={('fulldata_applicant_id', 'class_id')},
        ),
    ]
