# Generated by Django 5.0.9 on 2024-11-14 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0011_rename_tblstudentprospectus_tblprospectus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblprospectus',
            name='program_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DangoDBApp.tblprogram'),
        ),
    ]
