# Generated by Django 5.1 on 2024-08-22 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0011_tbladdpersonaldata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblstudentpersonaldata',
            name='acr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
