# Generated by Django 5.0.9 on 2024-10-07 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0011_alter_tblstudentpersonaldata_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblstudentpersonaldata',
            name='basicdata_applicant_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='related_family_data', to='DangoDBApp.tblstudentbasicinfo'),
            preserve_default=False,
        ),
    ]
