# Generated by Django 5.0.9 on 2024-11-01 11:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0012_alter_tblstudentenlistedsubjects_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblstudentenlistedsubjects',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tblstudentenlistedsubjects',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tblstudentenlistedsubjects',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tblstudentenlistedsubjects',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
