# Generated by Django 5.0.9 on 2024-10-07 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0012_tblstudentpersonaldata_basicdata_applicant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblstudentpersonaldata',
            name='basicdata_applicant_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='related_basic_data', to='DangoDBApp.tblstudentbasicinfo'),
        ),
    ]
