# Generated by Django 5.0.8 on 2024-08-26 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0012_alter_tblstudentpersonaldata_acr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblstudentfamilybackground',
            name='father_company',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tblstudentfamilybackground',
            name='father_contact_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tblstudentfamilybackground',
            name='father_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='tblstudentfamilybackground',
            name='father_fname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tblstudentfamilybackground',
            name='father_income',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tblstudentfamilybackground',
            name='father_lname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tblstudentfamilybackground',
            name='father_mname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tblstudentfamilybackground',
            name='father_occupation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tblstudentfamilybackground',
            name='guardian_contact_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tblstudentfamilybackground',
            name='guardian_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='tblstudentfamilybackground',
            name='guardian_fname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tblstudentfamilybackground',
            name='guardian_lname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tblstudentfamilybackground',
            name='guardian_mname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tblstudentfamilybackground',
            name='guardian_relation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tblstudentfamilybackground',
            name='mother_company',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tblstudentfamilybackground',
            name='mother_contact_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tblstudentfamilybackground',
            name='mother_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='tblstudentfamilybackground',
            name='mother_fname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tblstudentfamilybackground',
            name='mother_income',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tblstudentfamilybackground',
            name='mother_lname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tblstudentfamilybackground',
            name='mother_mname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tblstudentfamilybackground',
            name='mother_occupation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
