# Generated by Django 5.0.9 on 2024-11-16 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0012_alter_tblprospectus_program_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblStudentEnlistedOnSemesters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fulldata_applicant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DangoDBApp.tblstudentpersonaldata')),
                ('semester_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DangoDBApp.tblsemester')),
            ],
        ),
    ]
