# Generated by Django 5.0.9 on 2024-11-06 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0013_tblstudentenlistedsubjects_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblclass',
            name='created_at',
        ),
    ]
