# Generated by Django 5.0.9 on 2024-11-16 10:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0013_tblstudentenlistedonsemesters'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblstudentenlistedonsemesters',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tblstudentenlistedonsemesters',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tblstudentenlistedonsemesters',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tblstudentenlistedonsemesters',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
