# Generated by Django 5.0.8 on 2024-08-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0013_alter_tblstudentfamilybackground_father_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblstudentacademichistory',
            name='elementary_graduate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tblstudentacademichistory',
            name='junior_graduate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tblstudentacademichistory',
            name='ncae_year_taken',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tblstudentacademichistory',
            name='senior_graduate',
            field=models.IntegerField(),
        ),
    ]
