# Generated by Django 5.0.8 on 2024-08-26 16:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0014_alter_tblstudentacademichistory_elementary_graduate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblstudentpersonaldata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
