# Generated by Django 5.0.9 on 2024-11-21 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0014_tblstudentenlistedonsemesters_created_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tblstudentpersonaldata',
            unique_together={('f_name', 'l_name')},
        ),
    ]
