# Generated by Django 5.0.9 on 2024-11-06 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0014_remove_tblclass_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblclass',
            name='updated_at',
        ),
    ]
