# Generated by Django 5.0.9 on 2024-11-21 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0015_alter_tblstudentpersonaldata_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tblstudentbasicinfo',
            unique_together={('first_name', 'last_name')},
        ),
    ]
