# Generated by Django 5.0.9 on 2024-11-08 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0015_remove_tblclass_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblstudentenlistedsubjects',
            name='status',
            field=models.CharField(default='enlisted', max_length=50),
        ),
        migrations.AlterField(
            model_name='tblstudentpersonaldata',
            name='status',
            field=models.CharField(choices=[('officially enrolled', 'officially enrolled'), ('pending', 'pending'), ('verified', 'verified'), ('rejected', 'rejected'), ('initially enrolled', 'initially enrolled')], default='pending', max_length=20),
        ),
    ]
