# Generated by Django 5.0.8 on 2024-09-02 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0015_tblstudentpersonaldata_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tblstudentpersonaldata',
            old_name='gender',
            new_name='sex',
        ),
        migrations.AlterField(
            model_name='tbladdpersonaldata',
            name='city_contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tbladdpersonaldata',
            name='province_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tbladdpersonaldata',
            name='province_contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tblstudentfamilybackground',
            name='father_fname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tblstudentfamilybackground',
            name='father_income',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tblstudentfamilybackground',
            name='father_lname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tblstudentfamilybackground',
            name='father_mname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tblstudentfamilybackground',
            name='guardian_fname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tblstudentfamilybackground',
            name='guardian_lname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tblstudentfamilybackground',
            name='guardian_mname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tblstudentfamilybackground',
            name='guardian_relation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tblstudentfamilybackground',
            name='mother_fname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tblstudentfamilybackground',
            name='mother_lname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tblstudentfamilybackground',
            name='mother_mname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tblstudentpersonaldata',
            name='birth_place',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tblstudentpersonaldata',
            name='m_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tblstudentpersonaldata',
            name='marital_status',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='tblstudentpersonaldata',
            name='student_id',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
