# Generated by Django 5.0.8 on 2024-09-02 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0016_rename_gender_tblstudentpersonaldata_sex_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblstudentacademicbackground',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DangoDBApp.TblProgram'),
        ),
        migrations.AlterField(
            model_name='tblstudentacademichistory',
            name='college_address',
            field=models.TextField(blank=True, default='Not Provided', null=True),
        ),
        migrations.AlterField(
            model_name='tblstudentacademichistory',
            name='college_honors',
            field=models.TextField(blank=True, default='None', null=True),
        ),
        migrations.AlterField(
            model_name='tblstudentacademichistory',
            name='program',
            field=models.TextField(blank=True, default='Not Specified', null=True),
        ),
        migrations.AlterField(
            model_name='tblstudentacademichistory',
            name='elementary_graduate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tblstudentacademichistory',
            name='elementary_honors',
            field=models.TextField(blank=True, default='None', null=True),
        ),
        migrations.AlterField(
            model_name='tblstudentacademichistory',
            name='junior_graduate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tblstudentacademichistory',
            name='junior_honors',
            field=models.TextField(blank=True, default='None', null=True),
        ),
        migrations.AlterField(
            model_name='tblstudentacademichistory',
            name='latest_college',
            field=models.TextField(blank=True, default='Not Provided', null=True),
        ),
        migrations.AlterField(
            model_name='tblstudentacademichistory',
            name='ncae_grade',
            field=models.CharField(blank=True, default='Unknown', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tblstudentacademichistory',
            name='ncae_year_taken',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tblstudentacademichistory',
            name='senior_graduate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tblstudentacademichistory',
            name='senior_honors',
            field=models.TextField(blank=True, default='None', null=True),
        ),
    ]
