# Generated by Django 5.0.9 on 2024-11-22 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0017_tblstudentgrades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblstudentpersonaldata',
            name='status',
            field=models.CharField(choices=[('officially enrolled', 'officially enrolled'), ('pending', 'pending'), ('rejected', 'rejected'), ('unverified', 'unverified'), ('initially enrolled', 'initially enrolled')], default='pending', max_length=20),
        ),
    ]
