# Generated by Django 5.0.8 on 2024-09-06 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0017_alter_tblstudentacademicbackground_program_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblStudentBasicInfoApplications',
            fields=[
                ('student_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=11)),
                ('birth_date', models.DateField()),
                ('sex', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='tblstudentacademicbackground',
            old_name='program',
            new_name='program',
        ),
        migrations.RemoveField(
            model_name='tbladdpersonaldata',
            name='email',
        ),
        migrations.AddField(
            model_name='tblstudentpersonaldata',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
