# Generated by Django 5.0.9 on 2024-11-24 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0018_alter_tblstudentpersonaldata_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblEmailNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_id', models.IntegerField()),
                ('notification_type', models.CharField(max_length=50)),
                ('recipients_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['semester_id', 'created_at'], name='DangoDBApp__semeste_81c464_idx')],
            },
        ),
    ]
