# Generated by Django 5.0.8 on 2024-09-06 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0018_tblstudentbasicinfo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblstudentbasicinfo',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
