# Generated by Django 5.0.8 on 2024-09-07 02:32

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0019_tblstudentbasicinfo_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblstudentbasicinfo',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tblstudentbasicinfo',
            name='campus',
            field=models.CharField(max_length=225, blank=True),
        ),
    ]
