# Generated by Django 5.0.9 on 2024-11-25 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0020_tblregistrarmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblregistrarmessage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tblregistrarmessage',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
