# Generated by Django 5.0.8 on 2024-09-07 06:01

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0020_tblstudentbasicinfo_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblstudentbasicinfoapplications',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tblstudentbasicinfoapplications',
            name='student_id',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, unique=True),
        ),
    ]
