# Generated by Django 5.0.9 on 2024-11-26 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0021_tblregistrarmessage_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblregistrarmessage',
            name='is_deleted',
        ),
    ]
