# Generated by Django 5.0.8 on 2024-09-07 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0021_tblstudentbasicinfo_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblstudentbasicinfoapplications',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tblstudentbasicinfoapplications',
            name='campus',
            field=models.CharField(max_length=225),
        ),
    ]
