# Generated by Django 5.0.9 on 2024-11-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0022_remove_tblregistrarmessage_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblregistrarmessage',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tblregistrarmessage',
            name='testfield',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
