# Generated by Django 5.0.8 on 2024-09-07 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0022_alter_tblstudentbasicinfo_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblstudentbasicinfoapplications',
            name='auto_generated',
            field=models.BooleanField(default=True),
        ),
    ]
