# Generated by Django 5.0.9 on 2024-11-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0023_tblregistrarmessage_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblstudentpersonaldata',
            name='status',
            field=models.CharField(choices=[('officially enrolled', 'officially enrolled'), ('pending', 'pending'), ('rejected', 'rejected'), ('unverified', 'unverified'), ('initially enrolled', 'initially enrolled')], default='unverified', max_length=20),
        ),
    ]
