# Generated by Django 5.0.9 on 2024-09-12 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0023_tblstudentbasicinfo_auto_generated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblstudentbasicinfoapplications',
            name='auto_generated',
        ),
        migrations.RemoveField(
            model_name='tblstudentbasicinfoapplications',
            name='student_id',
        ),
        migrations.AddField(
            model_name='tblstudentbasicinfoapplications',
            name='applicant_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tblstudentbasicinfoapplications',
            name='is_transfee',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tblstudentbasicinfoapplications',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tblstudentbasicinfoapplications',
            name='program',
            field=models.CharField(default=1, max_length=225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tblstudentbasicinfoapplications',
            name='suffix',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
