# Generated by Django 5.0.9 on 2024-09-12 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0024_remove_tblstudentbasicinfoapplications_auto_generated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblStudentBasicInfo',
            fields=[
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('suffix', models.CharField(blank=True, max_length=100, null=True)),
                ('is_transfee', models.BooleanField()),
                ('contact_number', models.CharField(max_length=11)),
                ('address', models.TextField()),
                ('campus', models.CharField(max_length=225)),
                ('program', models.CharField(max_length=225)),
                ('birth_date', models.DateField()),
                ('sex', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('accepted', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TblStudentPersonalDataApplications',
            fields=[
                ('f_name', models.CharField(max_length=100)),
                ('m_name', models.CharField(blank=True, max_length=100, null=True)),
                ('l_name', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('birth_place', models.TextField()),
                ('marital_status', models.CharField(max_length=7)),
                ('religion', models.CharField(max_length=70)),
                ('country', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('acr', models.CharField(blank=True, max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='tbladdpersonaldata',
            old_name='stdnt_id',
            new_name='student_id',
        ),
        migrations.RenameField(
            model_name='tblstudentacademicbackground',
            old_name='stdnt_id',
            new_name='student_id',
        ),
        migrations.RenameField(
            model_name='tblstudentacademichistory',
            old_name='stdnt_id',
            new_name='student_id',
        ),
        migrations.RenameField(
            model_name='tblstudentfamilybackground',
            old_name='stdnt_id',
            new_name='student_id',
        ),
        migrations.AlterField(
            model_name='tblstudentpersonaldata',
            name='student_id',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='TblStudentAcademicBackgroundApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_in', models.TextField(null=True)),
                ('student_type', models.CharField(max_length=30)),
                ('semester_entry', models.CharField(max_length=20)),
                ('year_entry', models.IntegerField()),
                ('year_graduate', models.IntegerField()),
                ('application_type', models.CharField(max_length=15)),
                ('active', models.BooleanField(default=True)),
                ('applicant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DangoDBApp.tblstudentpersonaldata')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DangoDBApp.tbldepartment')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DangoDBApp.tblprogram')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TblStudentFamilyBackgroundApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_fname', models.CharField(blank=True, max_length=100, null=True)),
                ('father_mname', models.CharField(blank=True, max_length=100, null=True)),
                ('father_lname', models.CharField(blank=True, max_length=100, null=True)),
                ('father_contact_number', models.CharField(blank=True, max_length=30, null=True)),
                ('father_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('father_occupation', models.TextField(blank=True, null=True)),
                ('father_income', models.IntegerField(blank=True, null=True)),
                ('father_company', models.TextField(blank=True, null=True)),
                ('mother_fname', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_mname', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_lname', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_contact_number', models.CharField(blank=True, max_length=30, null=True)),
                ('mother_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mother_occupation', models.TextField(blank=True, null=True)),
                ('mother_income', models.TextField(blank=True, null=True)),
                ('mother_company', models.TextField(blank=True, null=True)),
                ('guardian_fname', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_mname', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_lname', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_relation', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_contact_number', models.CharField(blank=True, max_length=30, null=True)),
                ('guardian_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('active', models.BooleanField(default=True)),
                ('applicant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DangoDBApp.tblstudentpersonaldataapplications')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TblStudentAcademicHistoryApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elementary_school', models.TextField(default='Not Provided')),
                ('elementary_address', models.TextField(default='Not Provided')),
                ('elementary_honors', models.TextField(blank=True, default='None', null=True)),
                ('elementary_graduate', models.IntegerField(blank=True, null=True)),
                ('junior_highschool', models.TextField(default='Not Provided')),
                ('junior_address', models.TextField(default='Not Provided')),
                ('junior_honors', models.TextField(blank=True, default='None', null=True)),
                ('junior_graduate', models.IntegerField(blank=True, null=True)),
                ('senior_highschool', models.TextField(default='Not Provided')),
                ('senior_address', models.TextField(default='Not Provided')),
                ('senior_honors', models.TextField(blank=True, default='None', null=True)),
                ('senior_graduate', models.IntegerField(blank=True, null=True)),
                ('ncae_grade', models.CharField(blank=True, default='Unknown', max_length=50, null=True)),
                ('ncae_year_taken', models.IntegerField(blank=True, null=True)),
                ('latest_college', models.TextField(blank=True, default='Not Provided', null=True)),
                ('college_address', models.TextField(blank=True, default='Not Provided', null=True)),
                ('college_honors', models.TextField(blank=True, default='None', null=True)),
                ('program', models.TextField(blank=True, default='Not Specified', null=True)),
                ('active', models.BooleanField(default=True)),
                ('applicant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DangoDBApp.tblstudentpersonaldataapplications')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TblAddPersonalDataApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_address', models.TextField()),
                ('province_address', models.TextField(blank=True, null=True)),
                ('contact_number', models.CharField(max_length=30)),
                ('city_contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('province_contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('citizenship', models.CharField(max_length=70)),
                ('active', models.BooleanField(default=True)),
                ('applicant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DangoDBApp.tblstudentpersonaldataapplications')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
