# Generated by Django 5.0.9 on 2024-09-13 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0025_tblstudentbasicinfo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tblstudentbasicinfo',
            old_name='is_transfee',
            new_name='is_transferee',
        ),
        migrations.RenameField(
            model_name='tblstudentbasicinfoapplications',
            old_name='is_transfee',
            new_name='is_transferee',
        ),
        migrations.AddField(
            model_name='tblstudentpersonaldata',
            name='suffix',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tblstudentpersonaldataapplications',
            name='suffix',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
