# Generated by Django 5.0.9 on 2024-09-13 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0026_rename_is_transfee_tblstudentbasicinfo_is_transferee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblstudentbasicinfo',
            name='year_level',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tblstudentbasicinfoapplications',
            name='year_level',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
