# Generated by Django 5.0.9 on 2024-09-14 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0028_remove_tblstudentbasicinfo_accepted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblstudentbasicinfo',
            name='address',
        ),
        migrations.RemoveField(
            model_name='tblstudentbasicinfo',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='tblstudentbasicinfo',
            name='campus',
        ),
        migrations.RemoveField(
            model_name='tblstudentbasicinfo',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='tblstudentbasicinfo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='tblstudentbasicinfo',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='tblstudentbasicinfo',
            name='is_transferee',
        ),
        migrations.RemoveField(
            model_name='tblstudentbasicinfo',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='tblstudentbasicinfo',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='tblstudentbasicinfo',
            name='program',
        ),
        migrations.RemoveField(
            model_name='tblstudentbasicinfo',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='tblstudentbasicinfo',
            name='suffix',
        ),
        migrations.RemoveField(
            model_name='tblstudentbasicinfo',
            name='year_level',
        ),
    ]
