# Generated by Django 5.0.9 on 2024-09-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0029_remove_tblstudentbasicinfo_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblstudentbasicinfoapplications',
            name='accepted',
        ),
        migrations.AddField(
            model_name='tblstudentbasicinfoapplications',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
