# Generated by Django 5.0.9 on 2024-09-16 15:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0033_alter_tblstudentbasicinfo_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblstudentbasicinfo',
            name='student_id',
            field=models.CharField(max_length=13, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='invalid_student_id', message='Student ID must be in the format YYYY-DD-NNNN, where YYYY is the year, DD is the department id (1 or 2 digits), and NNNNN is the student number (5 digits).', regex='^\\d{4}-\\d{1,2}-\\d{5}$')]),
        ),
    ]
