# Generated by Django 5.0.9 on 2024-09-16 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0034_alter_tblstudentbasicinfo_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblstudentbasicinfo',
            name='applicant_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='DangoDBApp.tblstudentbasicinfoapplications'),
        ),
        migrations.AlterField(
            model_name='tblstudentbasicinfo',
            name='student_id',
            field=models.CharField(max_length=13, primary_key=True, serialize=False),
        ),
    ]
