# Generated by Django 5.0.9 on 2024-09-17 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0035_alter_tblstudentbasicinfo_applicant_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblstudentbasicinfo',
            name='student_id',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
