# Generated by Django 5.0.9 on 2024-09-19 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0037_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblstudentbasicinfo',
            name='default_pass',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
