# Generated by Django 5.0.9 on 2024-09-19 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0038_tblstudentbasicinfo_default_pass'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tblstudentbasicinfo',
            old_name='default_pass',
            new_name='pswrd',
        ),
    ]
