# Generated by Django 5.0.9 on 2024-09-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0039_rename_default_pass_tblstudentbasicinfo_pswrd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblstudentbasicinfo',
            name='student_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
