# Generated by Django 5.0.9 on 2024-09-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0040_alter_tblstudentbasicinfo_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblBugReport',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_data', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
