# Generated by Django 5.0.9 on 2024-09-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DangoDBApp', '0041_tblbugreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblbugreport',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
